FROM nvcr.io/nvidia/pytorch:24.10-py3

# maybe we also have a requirements.txt file
# COPY ./requirements.txt /workspace/requirements.txt
# RUN pip install -r requirements.txt

# COPY ./project /workspace/project
# ENTRYPOINT ["python"]
# CMD ["/workspace/project/train.py"] 
ARG WORKSPACE